### ISSUE TITLE
what are the licensing for these mods? 

### ISSUE THREAD

**Issue by RakibRyan** [jpfrts/bigzomboid#1]
Can I make some changes of myself and post a version of these?

**Comment by jpfrts** [comment]
> Can I make some changes of myself and post a version of these?

Hey, actually this repository's been forgotten visible and it was just a backup of the mods from my server. All the mods used are listed on Steam Workshop where you can ask the developers directly :)

**Comment by jpfrts** [comment]
> Can I make some changes of myself and post a version of these?

Hey, actually this repository's been forgotten visible and it was just a backup of the mods from my server. All the mods used are listed on Steam Workshop where you can ask the developers directly :)
